### ISSUE TITLE
开启显示有错误提示

### ISSUE THREAD

**Issue by iranee** [imkratos/AliyupanAutoSignin#1]
result=$(get_json_value $sign "success")
echo $result

sed: unmatched 'u'
awk: cmd. line:1: Unexpected token
签到成功

**Comment by imkratos** [comment]
> result=$(get_json_value $sign "success") echo $result
> 
> sed: unmatched 'u' awk: cmd. line:1: Unexpected token 签到成功

恩，这个是因为json解析 有问题，因为懒得去仔细解析了，如果需要结果，可以直接 `echo $sign`

**Comment by iranee** [comment]
能登陆就行。估计是有些NAS系统的sed 或者 awk参数不齐全

**Comment by Cuzzie** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Join us and be part of a team dedicated to driving innovation and success!

## How to Apply:
To apply for this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.kennethtom, @jluo41, @pengqianhan, @Carlos-Zen, @vbossica, @r007, @kookia11, @chatPower, @thiross, @VikingDadMedic, @bcui2020, @senarukana, @qivhou, @Gerrit-Jan-Dreyer, @jayendranarumugam, @ayue870729, @11041104s, @physihan, @intergalacticmammoth, @joscordeiro
